version: "3"
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - MODE_ENV=production
    env_file:
      - ./.env
    command: npm run start-dev
