version: "3"
services:
  node-app:
    container_name: 'express-node-app'
    ports:
      - "4000:4000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example